name: Build and Release (Optimized)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  ELECTRON_CACHE: .electron
  ELECTRON_BUILDER_CACHE: .cache/electron-builder

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Cache Electron binaries
      uses: actions/cache@v3
      with:
        path: |
          .electron
          .cache
          ~/.cache/electron
          ~/AppData/Local/electron/Cache
        key: ${{ runner.os }}-electron-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-electron-
          
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Clean installation (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        npm cache clean --force
        Remove-Item -Recurse -Force node_modules -ErrorAction SilentlyContinue
        Remove-Item -Force package-lock.json -ErrorAction SilentlyContinue
        
    - name: Install dependencies
      run: |
        npm install
        npx electron-builder install-app-deps
        
    - name: Verify electron installation
      run: npx electron --version
      
    - name: Build application (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $env:ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES="true"
        npm run build:win
      timeout-minutes: 45
      
    - name: Build application (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        export CSC_IDENTITY_AUTO_DISCOVERY=false
        npm run build:mac
      timeout-minutes: 45
      
    - name: Build application (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: npm run build:linux
      timeout-minutes: 45
      
    - name: Upload Windows artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-builds
        path: |
          dist/*.exe
          dist/*.exe.blockmap
        retention-days: 7
        if-no-files-found: error
          
    - name: Upload macOS artifacts
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: macos-builds
        path: |
          dist/*.dmg
          dist/*.dmg.blockmap
        retention-days: 7
        if-no-files-found: error
          
    - name: Upload Linux artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-builds
        path: |
          dist/*.AppImage
          dist/*.deb
        retention-days: 7
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Display structure
      run: |
        echo "Downloaded files structure:"
        find . -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" \) -ls
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows-builds/*
          macos-builds/*
          linux-builds/*
        name: Office Image Extractor ${{ github.ref_name }}
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
        generate_release_notes: true
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
