name: Windows Release Build

on:
  push:
    # バージョン指定つきタグがプッシュされた時のみ実行
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      # Actions の基本設定
      - name: Check out Git repositry
        uses: actions/checkout@v4

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 依存パッケージのインストール
      - name: Install dependencies
        env:
          # Sharp のプリコンパイルされたバイナリを使用
          npm_config_sharp_binary_host: https://github.com/lovell/sharp-libvips/releases/download/
          npm_config_sharp_libvips_binary_host: https://github.com/lovell/sharp-libvips/releases/download/
          # node-gyp のビルドを回避
          npm_config_build_from_source: false
          SHARP_IGNORE_GLOBAL_LIBVIPS: 1
        run: npm ci

      #### webpackなどによるビルドが必要なとき ####
      # - name: Build
        # run: npm run build

      # Windows向けアプリケーションをGitHub releases へデプロイ
      - name: Deploy to GitHub Releases
        env:
          # GITHUB_TOKEN は自動生成されるのでとくに設定は不要
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # NPM スクリプト名は 'release' にすることが必須
        run: npm run release