name: GitHub CI

on:
  push:
    # バージョン指定つきタグがプッシュされた時のみ実行
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        # クロスプラットフォーム・ビルド
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      # Actions の基本設定
      - name: Check out Git repositry
        uses: actions/checkout@v4

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 依存パッケージのインストール
      - name: Install dependencies
        run: npm ci

      # Sharp の再ビルド（クロスプラットフォーム対応）
      - name: Rebuild native dependencies
        run: npm rebuild

      #### webpackなどによるビルドが必要なとき ####
      # - name: Build
        # run: npm run build

      # GitHub releases へデプロイ
      - name: Deploy
        env:
          # GITHUB_TOKEN は自動生成されるのでとくに設定は不要
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # NPM スクリプト名は 'release' にすることが必須
        run: npm run release